import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';
import ThemeProvider from '@/providers/theme.provider';
import useTheme from '@/hooks/use-theme';

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-archivo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className="scroll-smooth">
      <ThemeProvider className={`${archivo.className} ${archivo.variable}`}>
        <div className="main-layout md:p-14 p-4 overflow-clip">
          <div className="primary-gradient" />
          <div className="accent-gradient" />
          <div style={{ position: 'relative', zIndex: 12 }}>
            <Nav />
            {children}
          </div>
        </div>
      </ThemeProvider>
    </html>
  );
}
