import type { Metadata } from 'next';
import { Archivo, Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';

const inter = Inter({ subsets: ['latin'] });

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-archivo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${archivo.className} ${archivo.variable}`}>
        <div className="main-layout p-14 overflow-hidden">
          <div className="primary-gradient" />
          <div className="accent-gradient" />
          <div style={{ position: 'relative', zIndex: 12 }}>
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
